elements = [
    {"name": "Hydrogen", "symbol": "H", "atomic_number": 1, "atomic_mass": 1.008, "electronic_config": "1s1"},
    {"name": "Helium", "symbol": "He", "atomic_number": 2, "atomic_mass": 4.003, "electronic_config": "1s2"},
    {"name": "Lithium", "symbol": "Li", "atomic_number": 3, "atomic_mass": 6.941, "electronic_config": "[He] 2s1"},
    {"name": "Beryllium", "symbol": "Be", "atomic_number": 4, "atomic_mass": 9.012, "electronic_config": "[He] 2s2"},
    {"name": "Boron", "symbol": "B", "atomic_number": 5, "atomic_mass": 10.81, "electronic_config": "[He] 2s2 2p1"},
    {"name": "Carbon", "symbol": "C", "atomic_number": 6, "atomic_mass": 12.01, "electronic_config": "[He] 2s2 2p2"},
    {"name": "Nitrogen", "symbol": "N", "atomic_number": 7, "atomic_mass": 14.01, "electronic_config": "[He] 2s2 2p3"},
    {"name": "Oxygen", "symbol": "O", "atomic_number": 8, "atomic_mass": 16.00, "electronic_config": "[He] 2s2 2p4"},
    {"name": "Fluorine", "symbol": "F", "atomic_number": 9, "atomic_mass": 19.00, "electronic_config": "[He] 2s2 2p5"},
    {"name": "Neon", "symbol": "Ne", "atomic_number": 10, "atomic_mass": 20.18, "electronic_config": "[He] 2s2 2p6"},
    {"name": "Sodium", "symbol": "Na", "atomic_number": 11, "atomic_mass": 22.99, "electronic_config": "[Ne] 3s1"},
    {"name": "Magnesium", "symbol": "Mg", "atomic_number": 12, "atomic_mass": 24.31, "electronic_config": "[Ne] 3s2"},
    {"name": "Aluminum", "symbol": "Al", "atomic_number": 13, "atomic_mass": 26.98, "electronic_config": "[Ne] 3s2 3p1"},
    {"name": "Silicon", "symbol": "Si", "atomic_number": 14, "atomic_mass": 28.09, "electronic_config": "[Ne] 3s2 3p2"},
    {"name": "Phosphorus", "symbol": "P", "atomic_number": 15, "atomic_mass": 30.97, "electronic_config": "[Ne] 3s2 3p3"},
    {"name": "Sulfur","symbol": "S", "atomic_number": 16, "atomic_mass": 32.07, "electronic_config": "[Ne] 3s2 3p4"},
    {"name": "Chlorine","symbol": "Cl", "atomic_number": 17, "atomic_mass": 35.45, "electronic_config": "[Ne] 3s2 3p5"},
    {"name": "Potassium","symbol": "K", "atomic_number": 19, "atomic_mass": 39.10, "electronic_config": "[Ar] 4s1"},
    {"name": "Calcium","symbol": "Ca", "atomic_number": 20, "atomic_mass": 40.08, "electronic_config": "[Ar] 4s2"},
    {"name": "Calcium", "symbol": "Ca", "atomic_number": 20, "atomic_mass": 40.08, "electronic_config": "[Ar] 4s2"},
    {"name": "Scandium", "symbol": "Sc", "atomic_number": 21, "atomic_mass": 44.96,
     "electronic_config": "[Ar] 3d1 4s2"},
    {"name": "Titanium", "symbol": "Ti", "atomic_number": 22, "atomic_mass": 47.87,
     "electronic_config": "[Ar] 3d2 4s2"},
    {"name": "Vanadium", "symbol": "V", "atomic_number": 23, "atomic_mass": 50.94, "electronic_config": "[Ar] 3d3 4s2"},
    {"name": "Chromium", "symbol": "Cr", "atomic_number": 24, "atomic_mass": 52.00,
     "electronic_config": "[Ar] 3d5 4s1"},
    {"name": "Manganese", "symbol": "Mn", "atomic_number": 25, "atomic_mass": 54.94,
     "electronic_config": "[Ar] 3d5 4s2"},
    {"name": "Iron", "symbol": "Fe", "atomic_number": 26, "atomic_mass": 55.85, "electronic_config": "[Ar] 3d6 4s2"},
    {"name": "Cobalt", "symbol": "Co", "atomic_number": 27, "atomic_mass": 58.93, "electronic_config": "[Ar] 3d7 4s2"},
    {"name": "Nickel", "symbol": "Ni", "atomic_number": 28, "atomic_mass": 58.69, "electronic_config": "[Ar] 3d8 4s2"},
    {"name": "Copper", "symbol": "Cu", "atomic_number": 29, "atomic_mass": 63.55, "electronic_config": "[Ar] 3d10 4s1"},
    {"name": "Zinc", "symbol": "Zn", "atomic_number": 30, "atomic_mass": 65.38, "electronic_config": "[Ar] 3d10 4s2"},
    {"name": "Gallium", "symbol": "Ga", "atomic_number": 31, "atomic_mass": 69.72,
     "electronic_config": "[Ar] 3d10 4s2 4p1"},
    {"name": "Germanium", "symbol": "Ge", "atomic_number": 32, "atomic_mass": 72.63,
     "electronic_config": "[Ar] 3d10 4s2 4p2"},
    {"name": "Arsenic", "symbol": "As", "atomic_number": 33, "atomic_mass": 74.92,
     "electronic_config": "[Ar] 3d10 4s2 4p3"},
    {"name": "Selenium", "symbol": "Se", "atomic_number": 34, "atomic_mass": 78.96,
     "electronic_config": "[Ar] 3d10 4s2 4p4"},
    {"name": "Bromine", "symbol": "Br", "atomic_number": 35, "atomic_mass": 79.90,
     "electronic_config": "[Ar] 3d10 4s2 4p5"},
    {"name": "Krypton", "symbol": "Kr", "atomic_number": 36, "atomic_mass": 83.80,
     "electronic_config": "[Ar] 3d10 4s2 4p6"},
    {"name": "Rubidium", "symbol": "Rb", "atomic_number": 37, "atomic_mass": 85.47, "electronic_config": "[Kr] 5s1"},
    {"name": "Strontium", "symbol": "Sr", "atomic_number": 38, "atomic_mass": 87.62, "electronic_config": "[Kr] 5s2"},
    {"name": "Yttrium", "symbol": "Y", "atomic_number": 39, "atomic_mass": 88.91, "electronic_config": "[Kr] 4d1 5s2"},
    {"name": "Zirconium", "symbol": "Zr", "atomic_number": 40, "atomic_mass": 91.22,
     "electronic_config": "[Kr] 4d2 5s2"},
    {"name": "Niobium", "symbol": "Nb", "atomic_number": 41, "atomic_mass": 92.91, "electronic_config": "[Kr] 4d4 5s1"},
    {"name": "Molybdenum", "symbol": "Mo", "atomic_number": 42, "atomic_mass": 95.94,
     "electronic_config": "[Kr] 4d5 5s1"},
    {"name": "Technetium", "symbol": "Tc", "atomic_number": 43, "atomic_mass": 98.00,
     "electronic_config": "[Kr] 4d5 5s2"},
    {"name": "Ruthenium", "symbol": "Ru", "atomic_number": 44, "atomic_mass": 101.07,
     "electronic_config": "[Kr] 4d6 5s1"},
    {"name": "Rhodium", "symbol": "Rh", "atomic_number": 45, "atomic_mass": 102.91,
     "electronic_config": "[Kr] 4d7 5s1"},
    {"name": "Palladium", "symbol": "Pd", "atomic_number": 46, "atomic_mass": 106.42, "electronic_config": "[Kr] 4d10"},
    {"name": "Silver", "symbol": "Ag", "atomic_number": 47, "atomic_mass": 107.87,
     "electronic_config": "[Kr] 4d10 5s1"},
    {"name": "Cadmium", "symbol": "Cd", "atomic_number": 48, "atomic_mass": 112.41,
     "electronic_config": "[Kr] 4d10 5s2"},
    {"name": "Indium", "symbol": "In", "atomic_number": 49, "atomic_mass": 114.82,
     "electronic_config": "[Kr] 4d10 5s2 5p1"},
    {"name": "Tin", "symbol": "Sn", "atomic_number": 50, "atomic_mass": 118.71,
     "electronic_config": "[Kr] 4d10 5s2 5p2"},
    {"name": "Antimony", "symbol": "Sb", "atomic_number": 51, "atomic_mass": 121.76,
     "electronic_config": "[Kr] 4d10 5s2 5p3"},
    {"name": "Tellurium", "symbol": "Te", "atomic_number": 52, "atomic_mass": 127.60,
     "electronic_config": "[Kr] 4d10 5s2 5p4"},
    {"name": "Iodine", "symbol": "I", "atomic_number": 53, "atomic_mass": 126.90,
     "electronic_config": "[Kr] 4d10 5s2 5p5"},
    {"name": "Xenon", "symbol": "Xe", "atomic_number": 54, "atomic_mass": 131.29,
     "electronic_config": "[Kr] 4d10 5s2 5p6"},
    {"name": "Cesium", "symbol": "Cs", "atomic_number": 55, "atomic_mass": 132.91, "electronic_config": "[Xe] 6s1"},
    {"name": "Barium", "symbol": "Ba", "atomic_number": 56, "atomic_mass": 137.33, "electronic_config": "[Xe] 6s2"},
    {"name": "Lanthanum", "symbol": "La", "atomic_number": 57, "atomic_mass": 138.91,
     "electronic_config": "[Xe] 5d1 6s2"},
    {"name": "Cerium", "symbol": "Ce", "atomic_number": 58, "atomic_mass": 140.12,
     "electronic_config": "[Xe] 4f1 5d1 6s2"},
    {"name": "Praseodymium", "symbol": "Pr", "atomic_number": 59, "atomic_mass": 140.91,
     "electronic_config": "[Xe] 4f3 6s2"},
    {"name": "Neodymium", "symbol": "Nd", "atomic_number": 60, "atomic_mass": 144.24,
     "electronic_config": "[Xe] 4f4 6s2"},
    {"name": "Promethium", "symbol": "Pm", "atomic_number": 61, "atomic_mass": 145.00,
     "electronic_config": "[Xe] 4f5 6s2"},
    {"name": "Samarium", "symbol": "Sm", "atomic_number": 62, "atomic_mass": 150.36,
     "electronic_config": "[Xe] 4f6 6s2"},
    {"name": "Europium", "symbol": "Eu", "atomic_number": 63, "atomic_mass": 151.96,
     "electronic_config": "[Xe] 4f7 6s2"},
    {"name": "Gadolinium", "symbol": "Gd", "atomic_number": 64, "atomic_mass": 157.25,
     "electronic_config": "[Xe] 4f7 5d1 6s2"},
    {"name": "Terbium", "symbol": "Tb", "atomic_number": 65, "atomic_mass": 158.93,
     "electronic_config": "[Xe] 4f9 6s2"},
    {"name": "Dysprosium", "symbol": "Dy", "atomic_number": 66, "atomic_mass": 162.50,
     "electronic_config": "[Xe] 4f10 6s2"},
    {"name": "Holmium", "symbol": "Ho", "atomic_number": 67, "atomic_mass": 164.93,
     "electronic_config": "[Xe] 4f11 6s2"},
    {"name": "Erbium", "symbol": "Er", "atomic_number": 68, "atomic_mass": 167.26,
     "electronic_config": "[Xe] 4f12 6s2"},
    {"name": "Thulium", "symbol": "Tm", "atomic_number": 69, "atomic_mass": 168.93,
     "electronic_config": "[Xe] 4f13 6s2"},
    {"name": "Ytterbium", "symbol": "Yb", "atomic_number": 70, "atomic_mass": 173.05,
     "electronic_config": "[Xe] 4f14 6s2"},
    {"name": "Lutetium", "symbol": "Lu", "atomic_number": 71, "atomic_mass": 174.97,
     "electronic_config": "[Xe] 4f14 5d1 6s2"},
    {"name": "Hafnium", "symbol": "Hf", "atomic_number": 72, "atomic_mass": 178.49,
     "electronic_config": "[Xe] 4f14 5d2 6s2"},
    {"name": "Tantalum", "symbol": "Ta", "atomic_number": 73, "atomic_mass": 180.95,
     "electronic_config": "[Xe] 4f14 5d3 6s2"},
    {"name": "Tungsten", "symbol": "W", "atomic_number": 74, "atomic_mass": 183.84,
     "electronic_config": "[Xe] 4f14 5d4 6s2"},
    {"name": "Rhenium", "symbol": "Re", "atomic_number": 75, "atomic_mass": 186.21,
     "electronic_config": "[Xe] 4f14 5d5 6s2"},
    {"name": "Osmium", "symbol": "Os", "atomic_number": 76, "atomic_mass": 190.23,
     "electronic_config": "[Xe] 4f14 5d6 6s2"},
    {"name": "Iridium", "symbol": "Ir", "atomic_number": 77, "atomic_mass": 192.22,
     "electronic_config": "[Xe] 4f14 5d7 6s2"},
    {"name": "Platinum", "symbol": "Pt", "atomic_number": 78, "atomic_mass": 195.08,
     "electronic_config": "[Xe] 4f14 5d9 6s1"},
    {"name": "Gold", "symbol": "Au", "atomic_number": 79, "atomic_mass": 196.97,
     "electronic_config": "[Xe] 4f14 5d10 6s1"},
    {"name": "Mercury", "symbol": "Hg", "atomic_number": 80, "atomic_mass": 200.59,
     "electronic_config": "[Xe] 4f14 5d10 6s2"},
    {"name": "Thallium", "symbol": "Tl", "atomic_number": 81, "atomic_mass": 204.38,
     "electronic_config": "[Xe] 4f14 5d10 6s2 6p1"},
    {"name": "Lead", "symbol": "Pb", "atomic_number": 82, "atomic_mass": 207.2,
     "electronic_config": "[Xe] 4f14 5d10 6s2 6p2"},
    {"name": "Bismuth", "symbol": "Bi", "atomic_number": 83, "atomic_mass": 208.98,
     "electronic_config": "[Xe] 4f14 5d10 6s2 6p3"},
    {"name": "Polonium", "symbol": "Po", "atomic_number": 84, "atomic_mass": 209,
     "electronic_config": "[Xe] 4f14 5d10 6s2 6p4"},
    {"name": "Astatine", "symbol": "At", "atomic_number": 85, "atomic_mass": 210,
     "electronic_config": "[Xe] 4f14 5d10 6s2 6p5"},
    {"name": "Radon", "symbol": "Rn", "atomic_number": 86, "atomic_mass": 222,
     "electronic_config": "[Xe] 4f14 5d10 6s2 6p6"},
    {"name": "Francium", "symbol": "Fr", "atomic_number": 87, "atomic_mass": 223, "electronic_config": "[Rn] 7s1"},
    {"name": "Radium", "symbol": "Ra", "atomic_number": 88, "atomic_mass": 226, "electronic_config": "[Rn] 7s2"},
    {"name": "Actinium", "symbol": "Ac", "atomic_number": 89, "atomic_mass": 227, "electronic_config": "[Rn] 6d1 7s2"},
    {"name": "Thorium", "symbol": "Th", "atomic_number": 90, "atomic_mass": 232.04,
     "electronic_config": "[Rn] 6d2 7s2"},
    {"name": "Protactinium", "symbol": "Pa", "atomic_number": 91, "atomic_mass": 231.04,
     "electronic_config": "[Rn] 5f2 6d1 7s2"},
    {"name": "Uranium", "symbol": "U", "atomic_number": 92, "atomic_mass": 238.03,
     "electronic_config": "[Rn] 5f3 6d1 7s2"},
    {"name": "Neptunium", "symbol": "Np", "atomic_number": 93, "atomic_mass": 237.05,
     "electronic_config": "[Rn] 5f4 6d1 7s2"},
    {"name": "Plutonium", "symbol": "Pu", "atomic_number": 94, "atomic_mass": 244, "electronic_config": "[Rn] 5f6 7s2"},
    {"name": "Plutonium", "symbol": "Pu", "atomic_number": 94, "atomic_mass": 244.06,
     "electronic_config": "[Rn] 5f6 7s2"},
    {"name": "Americium", "symbol": "Am", "atomic_number": 95, "atomic_mass": 243.06,
     "electronic_config": "[Rn] 5f7 7s2"},
    {"name": "Curium", "symbol": "Cm", "atomic_number": 96, "atomic_mass": 247.07,
     "electronic_config": "[Rn] 5f7 6d1 7s2"},
    {"name": "Berkelium", "symbol": "Bk", "atomic_number": 97, "atomic_mass": 247.07,
     "electronic_config": "[Rn] 5f9 7s2"},
    {"name": "Californium", "symbol": "Cf", "atomic_number": 98, "atomic_mass": 251.08,
     "electronic_config": "[Rn] 5f10 7s2"},
    {"name": "Einsteinium", "symbol": "Es", "atomic_number": 99, "atomic_mass": 252.08,
     "electronic_config": "[Rn] 5f11 7s2"},
    {"name": "Fermium", "symbol": "Fm", "atomic_number": 100, "atomic_mass": 257.10,
     "electronic_config": "[Rn] 5f12 7s2"},
    {"name": "Mendelevium", "symbol": "Md", "atomic_number": 101, "atomic_mass": 258.10,
     "electronic_config": "[Rn] 5f13 7s2"},
    {"name": "Nobelium", "symbol": "No", "atomic_number": 102, "atomic_mass": 259.10,
     "electronic_config": "[Rn] 5f14 7s2"},
    {"name": "Lawrencium", "symbol": "Lr", "atomic_number": 103, "atomic_mass": 262.11,
     "electronic_config": "[Rn] 5f14 7s2 7p1"},
    {"name": "Rutherfordium", "symbol": "Rf", "atomic_number": 104, "atomic_mass": 267.12,
     "electronic_config": "[Rn] 5f14 6d2 7s2"},
    {"name": "Dubnium", "symbol": "Db", "atomic_number": 105, "atomic_mass": 268,
     "electronic_config": "-"},
    {"name": "Seaborgium", "symbol": "Sg", "atomic_number": 106, "atomic_mass": 269,
     "electronic_config": "-"},
    {"name": "Bohrium", "symbol": "Bh", "atomic_number": 107, "atomic_mass": 270,
     "electronic_config": "-"},
    {"name": "Hassium", "symbol": "Hs", "atomic_number": 108, "atomic_mass": 269,
     "electronic_config": "-"},
    {"name": "Meitnerium", "symbol": "Mt", "atomic_number": 109, "atomic_mass": 277,
     "electronic_config": "-"},
    {"name": "Darmstadtium", "symbol": "Ds", "atomic_number": 110, "atomic_mass": 281,
     "electronic_config": "-"},
    {"name": "Roentgenium", "symbol": "Rg", "atomic_number": 111, "atomic_mass": 282,
     "electronic_config": "-"},
    {"name": "Copernicium", "symbol": "Cn", "atomic_number": 112, "atomic_mass": 285,
     "electronic_config": "-"},
    {"name": "Nihonium", "symbol": "Nh", "atomic_number": 113, "atomic_mass": 286,
     "electronic_config": "-"},
    {"name": "Flerovium", "symbol": "Fl", "atomic_number": 114, "atomic_mass": 290,
     "electronic_config": "-"},
    {"name": "Moscovium", "symbol": "Mc", "atomic_number": 115, "atomic_mass": 290,
     "electronic_config": "-"},
    {"name": "Livermorium", "symbol": "Lv", "atomic_number": 116, "atomic_mass": 293,
     "electronic_config": "-"},
    {"name": "Tennessine", "symbol": "Ts", "atomic_number": 117, "atomic_mass": 294,
     "electronic_config": "-"},
    {"name": "Oganesson", "symbol": "Og", "atomic_number": 118, "atomic_mass": 294,
     "electronic_config": "-"}
]
def print_element_list():
    print("  Name                  |   Symbol   |  Atomic Number |   Atomic Mass    ")
    print("-"*75)
    for element in elements:
        print(f"{element['name']:25}|{element['symbol']:12}|{element['atomic_number']:15}|{element['atomic_mass']:18}|{element['electronic_config']}")

# Ask the user to input the name of an element
name = input("Enter the name of an element: ")

# Search for the element in the list and print its properties
found = False
for element in elements:
    if name == element["name"]:
        print(f"The name of the element is {name}, its symbol is {element['symbol']}")
        print(f"Atomic number: {element['atomic_number']}")
        print(f"Atomic mass: {element['atomic_mass']}")
        print(f"Electronic configuration: {element['electronic_config']}")
        found = True
        break

# If the element was not found, print an error message
if not found:
    print(f"{name} not found in the list of elements. Please enter a valid element.")

# Ask the user if they want to see the full list of elements
show_list = input("Do you want to see a full list of elements? (Y/N): ")

# If the user wants to see the full list, call the print_element_list() function
if show_list == "Y":
    print_element_list()
